MESSAGE("FINDING HAGAMELITE LIB")
set(CMAKE_FIND_DEBUG_MODE TRUE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

set(
        FIND_HAGAME_PATHS
        /home/henry/CLionProjects/HaGameLite
)

find_path(
        HAGAME_INCLUDE_DIR hagame.h
        PATH_SUFFIXES include
        PATHS ${FIND_HAGAME_PATHS}
)
if(EMSCRIPTEN)
    MESSAGE("EMSCRIPTEN")
    find_library(HAGAME_LIBRARY
            NAMES HaGame
            PATH_SUFFIXES wasm
            PATHS ${FIND_HAGAME_PATHS}
            )
else()
    MESSAGE("UNIX")
    find_library(HAGAME_LIBRARY
            NAMES HaGame
            PATH_SUFFIXES lib
            PATHS ${FIND_HAGAME_PATHS}
            )
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

MESSAGE("FIND_HAGAME_PATHS = ${FIND_HAGAME_PATHS}")
MESSAGE("HAGAME_INCLUDE_DIR = ${HAGAME_INCLUDE_DIR}")
MESSAGE("HAGAME_LIBRARY = ${HAGAME_LIBRARY}")