MESSAGE("FINDING HAGAME2 LIB")
set(CMAKE_FIND_DEBUG_MODE TRUE)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
# The places to look for the tinyxml2 folders
set(
        FIND_HAGAME2_PATHS
        /home/henry/CLionProjects/HaGame2
)

find_path(
        HAGAME2_INCLUDE_DIR hagame.h
        PATH_SUFFIXES include
        PATHS ${FIND_HAGAME2_PATHS}
)
if(EMSCRIPTEN)
    MESSAGE("EMSCRIPTEN")
    find_library(HAGAME2_LIBRARY
            NAMES HaGame2
            PATH_SUFFIXES wasm
            PATHS ${FIND_HAGAME2_PATHS}
            )
else()
    MESSAGE("UNIX")
    find_library(HAGAME2_LIBRARY
            NAMES HaGame2
            PATH_SUFFIXES lib
            PATHS ${FIND_HAGAME2_PATHS}
            )
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

MESSAGE("FIND_HAGAME2_PATHS = ${FIND_HAGAME2_PATHS}")
MESSAGE("HAGAME2_INCLUDE_DIR = ${HAGAME2_INCLUDE_DIR}")
MESSAGE("HAGAME2_LIBRARY = ${HAGAME2_LIBRARY}")